name             'railsapp'
maintainer       'Guillermo Arias'
maintainer_email 'garias.arrieta@gmail.com'
license          'All rights reserved'
description      'Installs/Configures railsapp'
long_description 'Installs/Configures railsapp'
version          '0.1.0'

depends 'apt'
depends 'nginx'
depends 'locale'
depends 'mongodb'
depends 'rvm'
depends 'redisio'